name = "edgesidedocs"
type = "webpack"
account_id = "72d3d558198481df539e10372a7da9d7"
workers_dev = false
route = "docs.edgeside.org/*" 
zone_id = "4396e027f93fa1fde8796d09e5b10979" 
webpack_config = "webpack.config.js"

[vars]
ORIGIN_HOST = "davidfriar.github.io"
ORIGIN_PATH_PREFIX = "edgeside-docs/" 
ORIGIN_PROTOCOL = "https:"
ORIGIN_CACHE_TTL = 60
ORIGIN_CACHE_EVERYTHING = true
DEBUG=true
